backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "programmes"
    label: "Programmes"
    folder: "content/programmes"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Age", name: "age", widget: "string"}
      - label: Class
        name: classes
        widget: list
        fields:
          - label: Days
            name: days
            widget: list
            fields:
              - {label: Monday, name: monday, widget: boolean, default: false}
              - {label: Tuesday, name: tuesday, widget: boolean, default: false}
              - {label: Wednesday, name: wednesday, widget: boolean, default: false}
              - {label: Thursday, name: thursday, widget: boolean, default: false}
              - {label: Friday, name: friday, widget: boolean, default: false}
              - {label: Saturday, name: saturday, widget: boolean, default: false}
              - {label: Sunday, name: sunday, widget: boolean, default: false}
          - {label: "Time", name: "time", widget: "string", default: "3:30 - 4:20PM"}
          - {label: "Cost", name: "cost", widget: "string", default: "$120"}
          - {label: "Detail", name: "detail", widget: "string", default: ""}
      - {label: "Category", name: "category", widget: "select", options: ["Recreational", "Intermediate", "Advanced", "Service"]}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Additional Items"
        name: "items"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Is Ribbon?", name: is_ribbon, widget: boolean, default: false}
  - label: "Pages"
    name: "pages"
    files:
    - name: "general"
      label: "General"
      file: 'content/general.json'
      fields:
        - label: "Navigation Logo"
          name: "nav_logo"
          widget: "image"
          default: "static/images/uploads/hcg-logo_purple_half.png"
        - label: "Navigation Logo Inverted"
          name: "nav_logo_inv"
          widget: "image"
          default: "static/images/uploads/hcg-logo_white_half.png"
    - name: "homepage"
      label: "Homepage"
      file: "content/home.json"
      fields:
        - label: "Splash Heading"
          name: "splash_heading"
          widget: "string"
        - label: "Splash Subtitle"
          name: "splash_subtitle"
          widget: "string"
        - label: "Splash Button"
          name: "splash_button"
          widget: "string"
        - label: "Splash Link"
          name: "splash_link"
          widget: "string"
        - label: "Splash Image"
          name: "splash_image"
          widget: "image"
        - label: "Contact Title"
          name: "contact_title"
          widget: "string"
        - label: "Contact Subitle"
          name: "contact_subtitle"
          widget: "string"
        - label: "Contact Button Text"
          name: "contact_button"
          widget: "string"
        - label: "Home Tiles"
          name: "home_tiles"
          widget: "list"
          fields:
            - { label: Title, name: title, widget: string }
            - { label: Content, name: content, widget: string }
            - { label: Button, name: button, widget: string }
            - { label: Link, name: url, widget: string }
            - { label: Image, name: image, widget: image }
    - name: "nav"
      label: "Navigation"
      file: "content/nav.json"
      fields:
        - label: "Navigation Logo"
          name: "nav_logo"
          widget: "image"
          default: "static/images/uploads/hcg-logo_purple_half.png"
        - label: "Navigation Logo Inverted"
          name: "nav_logo_inv"
          widget: "image"
          default: "static/images/uploads/hcg-logo_white_half.png"
        - label: "Menu"
          name: "menu_items"
          widget: "list"
          allow_add: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
              default: "Link"
            - label: "Link"
              name: "url"
              widget: "string"
              default: "/"
            - label: "Icon"
              name: "icon"
              widget: "string"
        - label: "Programmes Dropdown"
          name: "dropdown"
          widget: "object"
          allow_add: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
              default: "Programmes"
            - label: "Link"
              name: "url"
              widget: "string"
              default: "/programmes"
            - label: "See All Text"
              name: "subtitle"
              widget: "string"
              default: "See All Programmes"
    - name: "foot"
      label: "Footer"
      file: "content/footer.json"
      fields:
        - label: "Gymnastics NZ Logo"
          name: "gnz_logo"
          widget: "image"
          default: "/images/uploads/gnz.png"
        - label: "ESST Logo"
          name: "est_logo"
          widget: "image"
          default: "/images/uploads/esst.jpg"
        - label: "Footer Text 1"
          name: "foot1"
          widget: "string"
        - label: "Footer Text 2"
          name: "foot2"
          widget: "string"
    - name: "about"
      label: "About"
      file: "content/about.json"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Subtitle"
          name: "subtitle"
          widget: "string"
        - label: "Content"
          name: "content"
          widget: "markdown"
    - name: "contact"
      label: "Contact"
      file: "content/contact.json"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Subitle"
          name: "subtitle"
          widget: "string"
        - label: "Phone Number"
          name: "phone"
          widget: "string"
        - label: "Phone Description"
          name: "phone_description"
          widget: "string"
        - label: "Office Hours"
          name: "hours"
          widget: "list"
          field:
            - {label: "Hour Item", name: "hour_item", widget: "string"}
        - label: "Phone Disclaimer"
          name: "phone_disclaimer"
          widget: "string"
        - label: "Email Description"
          name: "email_description"
          widget: "string"
        - label: "Email Contacts"
          name: "email"
          widget: "list"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Address", name: "url", widget: "string"}
    - name: "Enquiries"
      label: "enquiries"
      file: "content/enquiries.json"
      fields:
        - name: "Title"
          label: "title"
          widget: "string"
        - name: "Subtitle"
          label: "subtitle"
          widget: "string"
        - name: "Details Placeholder Text"
          label: "detailsPlaceholder"
          widget: "string"
    - name: "sponsors"
      label: "Sponsors"
      file: "content/sponsors.json"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Description"
          name: "description"
          widget: "string"
        - label: "Items"
          name: "items"
          widget: "list"
          fields:
            - label: "Name"
              name: "name"
              widget: "string"
            - label: "Image"
              name: "imageUrl"
              widget: "image"
    - name: "login"
      label: "Login"
      file: "content/login.json"
      fields:
        - label: "Card 1"
          name: "card_1"
          widget: "object"
          fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Button"
            name: "button"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"
        - label: "Card 2"
          name: "card_2"
          widget: "object"
          fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Button"
            name: "button"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"
  - name: "members"
    label: "Members"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "markdown", widget: "markdown"}
  