backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
    - name: "general"
      label: "General"
      file: 'content/general.json'
      fields:
        - label: "Navigation Logo"
          name: "nav_logo"
          widget: "image"
          default: "static/images/uploads/hcg-logo_purple_half.png"
        - label: "Navigation Logo Inverted"
          name: "nav_logo_inv"
          widget: "image"
          default: "static/images/uploads/hcg-logo_white_half.png"
    - name: "homepage"
      label: "Homepage"
      file: "content/home.json"
      fields:
        - label: "Splash Heading"
          name: "splash_heading"
          widget: "string"
        - label: "Splash Subtitle"
          name: "splash_subtitle"
          widget: "string"
        - label: "Splash Button"
          name: "splash_button"
          widget: "string"
        - label: "Splash Link"
          name: "splash_link"
          widget: "string"
        - label: "About Title"
          name: "about_title"
          widget: "string"
        - label: "About Subtitle"
          name: "about_subtitle"
          widget: "text"
        - label: "About Image"
          name: "about_image"
          widget: "image"
          default: ""
        - label: "About Button"
          name: "about_button"
          widget: "string"
        - label: "Programmes Title"
          name: "programmes_title"
          widget: "string"
        - label: "Programmes Subtitle"
          name: "programmes_subtitle"
          widget: "string"
        - label: "Programmes Column 1 Title"
          name: "col1_title"
          widget: "string"
        - label: "Programmes Column 1 Description"
          name: "col1_desc"
          widget: "string"
        - label: "Programmes Column 1 Button Text"
          name: "col1_button"
          widget: "string"
        - label: "Programmes Column 1 Button Link"
          name: "col1_link"
          widget: "string"
        - label: "Programmes Column 2 Title"
          name: "col2_title"
          widget: "string"
        - label: "Programmes Column 2 Description"
          name: "col2_desc"
          widget: "string"
        - label: "Programmes Column 2 Button Text"
          name: "col2_button"
          widget: "string"
        - label: "Programmes Column 2 Button Link"
          name: "col2_link"
          widget: "string"
        - label: "Programmes Column 3 Title"
          name: "col3_title"
          widget: "string"
        - label: "Programmes Column 3 Description"
          name: "col3_desc"
          widget: "string"
        - label: "Programmes Column 3 Button Text"
          name: "col3_button"
          widget: "string"
        - label: "Programmes Column 3 Button Link"
          name: "col3_link"
          widget: "string"
        - label: "Contact Title"
          name: "contact_title"
          widget: "string"
        - label: "Contact Subitle"
          name: "contact_subtitle"
          widget: "string"
        - label: "Contact Button Text"
          name: "contact_button"
          widget: "string"
    - name: "nav"
      label: "Navigation"
      file: "content/nav.json"
      fields:
        - label: "Navigation Logo"
          name: "nav_logo"
          widget: "image"
          default: "static/images/uploads/hcg-logo_purple_half.png"
        - label: "Navigation Logo Inverted"
          name: "nav_logo_inv"
          widget: "image"
          default: "static/images/uploads/hcg-logo_white_half.png"
        - label: "Menu"
          name: "menu_items"
          widget: "list"
          allow_add: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
              default: "Link"
            - label: "Link"
              name: "url"
              widget: "string"
              default: "/"
            - label: "Active"
              name: "is_active"
              widget: "boolean"
        - label: "Programmes Dropdown"
          name: "dropdown"
          widget: "object"
          allow_add: true
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
              default: "Programmes"
            - label: "Link"
              name: "url"
              widget: "string"
              default: "/programmes"
            - label: "See All Text"
              name: "subtitle"
              widget: "string"
              default: "See All Programmes"
    - name: "foot"
      label: "Footer"
      file: "content/footer.json"
      fields:
        - label: "Gymnastics NZ Logo"
          name: "gnz_logo"
          widget: "image"
          default: "/images/uploads/gnz.png"
        - label: "ESST Logo"
          name: "est_logo"
          widget: "image"
          default: "/images/uploads/esst.jpg"
        - label: "Footer Text 1"
          name: "foot1"
          widget: "string"
        - label: "Footer Text 2"
          name: "foot2"
          widget: "string"
    - name: "about"
      label: "About"
      file: "content/about.json"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Subtitle"
        name: "subtitle"
        widget: "string"
        - label: "Content"
          name: "content"
          widget: "markdown"
    - name: "contact"
      label: "Contact"
      file: "content/contact.json"
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Content"
          name: "content"
          widget: "markdown"